spring.application.name=biptag-api
server.port=8080
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM556355
spring.datasource.password=oracle1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dechbdkzvxnveivehzti.supabase.co/auth/v1
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG